### ISSUE TITLE
Overwriting non-terminal in sub-language: Generated code does not compile

### ISSUE THREAD

**Issue by ChristophRichter92** [MontiCore/monticore#23]
Language **math** extends **de.monticore.AssignmentExpressions**.

In math.mc4 I tried to overwrite **BinaryXorExpression** from https://github.com/MontiCore/monticore/blob/master/monticore-grammar/src/main/grammars/de/monticore/AssignmentExpressions.mc4:

`BinaryXorExpression implements Expression <110> = "----- will not be used ---- this removes BinaryXorExpression";`

The generated file _ASTBinaryXorExpressionBuilder.java_ uses fields which are not present in its super class.
=> does not compile 

I attached the corresponding files to this ticket.
Issue can also be found at commit: https://github.com/EmbeddedMontiArc/MontiMath/tree/4c100d226273f412fbb42c140c6c5ab0c98c4558

I used MontiCore Version 5.0.0

[BuildLog.txt](https://github.com/MontiCore/monticore/files/2029887/BuildLog.txt)
[Math.mc4.txt](https://github.com/MontiCore/monticore/files/2029889/Math.mc4.txt)
[ASTBinaryXorExpressionBuilder.java.txt](https://github.com/MontiCore/monticore/files/2029890/ASTBinaryXorExpressionBuilder.java.txt)

**Comment by briansinkovec** [comment]
The current release of the monticore base grammars (including the AssignmentExpressions grammar) are generated by version 4.5.5.1, which do not contain the new Builder features (inheritance, method overriding, etc.). In contrast, the release of the monticore generator provides the new Builder features.

In Summary: the generated BinaryXorExpression (from Math) expects the BinaryXorExpression (from AssignmentExpression) to inherit from an abstract **ASTNodeBuilder**, but it doesn't, so it leads to a compilation error.

You can (quick-)fix this problem by using the **monticore 5.0.1-SNAPSHOT version**.  It will be fixed by the next monticore release.
